# Generated by Django 5.2.17 on 2026-09-22 13:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormFieldDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=80, unique=True)),
                ('label', models.CharField(max_length=160)),
                ('section', models.CharField(max_length=80)),
                ('field_type', models.CharField(choices=[('text', 'Texto'), ('number', 'Numero'), ('date', 'Fecha'), ('choice', 'Lista'), ('boolean', 'Si/No')], default='text', max_length=20)),
                ('required', models.BooleanField(default=False)),
                ('editable', models.BooleanField(default=True)),
                ('options', models.JSONField(blank=True, default=list)),
                ('version', models.PositiveIntegerField(default=1)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['section', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Acta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('form_version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('RECEIVER_SIGNED', 'Recibe firmado'), ('DELIVERY_SIGNED', 'Entrega firmada'), ('PENDING_SUPERVISOR_ONE', 'Pendiente Supervisor uno'), ('REJECTED_BY_SUPERVISOR_ONE', 'Rechazada por Supervisor uno'), ('PENDING_SUPERVISOR_TWO', 'Pendiente Supervisor dos'), ('REJECTED_BY_SUPERVISOR_TWO', 'Rechazada por Supervisor dos'), ('COMPLETED', 'Completada'), ('GLPI_UPLOAD_PENDING', 'Pendiente de GLPI'), ('GLPI_UPLOADED', 'Archivada en GLPI'), ('GLPI_UPLOAD_FAILED', 'Error en GLPI')], default='DRAFT', max_length=40)),
                ('act_type', models.CharField(blank=True, max_length=80)),
                ('act_date', models.DateField(blank=True, null=True)),
                ('glpi_case_number', models.CharField(max_length=80, unique=True)),
                ('portfolio', models.CharField(blank=True, max_length=120)),
                ('rejection_reason', models.TextField(blank=True)),
                ('rejection_step', models.CharField(blank=True, max_length=40)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='actas/%Y/%m/')),
                ('glpi_upload_status', models.CharField(default='PENDING', max_length=30)),
                ('glpi_uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='actas_technician', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actas_created', to=settings.AUTH_USER_MODEL)),
                ('supervisor_one', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='actas_supervisor_one', to=settings.AUTH_USER_MODEL)),
                ('supervisor_two', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='actas_supervisor_two', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='actas.site')),
            ],
        ),
        migrations.CreateModel(
            name='ActaFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.JSONField(blank=True, default=dict)),
                ('source', models.CharField(default='MANUAL', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('acta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_values', to='actas.acta')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='actas.formfielddefinition')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('acta', 'definition'), name='unique_acta_field')],
            },
        ),
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature_type', models.CharField(choices=[('RECEIVE', 'Recibe'), ('DELIVERY', 'Entrega'), ('REVIEW', 'Reviso'), ('FINAL_APPROVAL', 'Aprobo')], max_length=20)),
                ('signer_name', models.CharField(max_length=160)),
                ('signer_document', models.CharField(blank=True, max_length=40)),
                ('signature_image', models.ImageField(blank=True, null=True, upload_to='signatures/%Y/%m/')),
                ('signature_hash', models.CharField(blank=True, max_length=128)),
                ('signed_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('method', models.CharField(default='DESKTOP', max_length=20)),
                ('acta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='actas.acta')),
                ('signed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('acta', 'signature_type'), name='unique_acta_signature')],
            },
        ),
    ]
