# Generated by Django 5.2.17 on 2026-09-29 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actas', '0004_acta_legal_consent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='acta',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='actas_receiver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='acta',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Borrador'), ('RECEIVER_SIGNED', 'Firma física del receptor registrada'), ('DELIVERY_SIGNED', 'Entrega firmada'), ('PENDING_SUPERVISOR_ONE', 'Pendiente Supervisor uno'), ('REJECTED_BY_SUPERVISOR_ONE', 'Rechazada por Supervisor uno'), ('PENDING_SUPERVISOR_TWO', 'Pendiente Supervisor dos'), ('REJECTED_BY_SUPERVISOR_TWO', 'Rechazada por Supervisor dos'), ('PENDING_RECEIVER_UPLOAD', 'Pendiente de escaneo firmado por el receptor'), ('COMPLETED', 'Completada'), ('GLPI_UPLOAD_PENDING', 'Pendiente de GLPI'), ('GLPI_UPLOADED', 'Archivada en GLPI'), ('GLPI_UPLOAD_FAILED', 'Error en GLPI')], default='DRAFT', max_length=40),
        ),
    ]
