# Generated by Django 5.2.17 on 2026-09-29 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actas', '0005_acta_receiver_alter_acta_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('defaults', models.JSONField(blank=True, default=dict, help_text='Valores por etiqueta de campo, por ejemplo: Acceso a HelpDesk GLPI: true.')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Portafolio',
                'verbose_name_plural': 'Catálogo de portafolios',
                'ordering': ['name'],
            },
        ),
    ]
