# Generated by Django 5.2.17 on 2026-10-05 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actas', '0006_portfolio_catalog'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Campaña',
                'verbose_name_plural': 'Catálogo de campañas',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='acta',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='actas', to='actas.campaigncatalog'),
        ),
    ]
