# Generated by Django 5.2.17 on 2026-09-29 14:46

import accounts.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrole',
            name='digital_signature',
            field=models.ImageField(blank=True, null=True, upload_to='supervisor-signatures/', validators=[django.core.validators.FileExtensionValidator(['png']), accounts.models.validate_signature_size]),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('TECHNICIAN', 'Tecnico'), ('SUPERVISOR_ONE', 'Supervisor uno'), ('SUPERVISOR_TWO', 'Supervisor dos'), ('RECEIVER', 'Receptor del activo'), ('AUDITOR', 'Auditor')], max_length=30),
        ),
    ]
